@startuml
object Customer
object Administrator
object Cupcake
object Order
object OrderLine
object Basket
object System

Customer "1" o-- "0..*" Order
Customer "1" *-- "1" Basket
Order "1" *-- "1..*" OrderLine
OrderLine "1" *-- "1" Cupcake
Basket "1" o-- "0..*" OrderLine
System "1" *-- "1" Administrator
System "1" o-- "1..*" Customer
@enduml